spring:
  application:
    name:
      categoria-service
  database:
    url:
      jdbc:postgresql://localhost:5432/db-microservice-categoria
    username:
      postgres
    password:
      abcd1234
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto:
        update:
    show-sql:
      true
    properties:
      hibernate:
        format_sql:
          true


